name: SonarQube Scan

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Optional: Playwright tests + coverage
      - name: Run Playwright tests
        run: npx playwright test --reporter=line

      - name: Check Sonar connectivity
        run: |
          echo "Checking $SONAR_HOST_URL"
          curl -I --fail "$SONAR_HOST_URL/api/server/version"
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


      # Nieuwe officiële scan actie
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: .
          scannerVersion: 7.2.0.5079
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      
      

